version: "3"
services:
  appserver:
    container_name: python-app-server
    hostname: localhost
    image: basic_python
    ports:
    - "5000:5000"
    depends_on:
    - postgres
    restart: on-failure
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    container_name: postgres
    privileged: true